# Symmetry Operations

### ★ Resubmission Changes -

Overall fixes - 
- Changed the definition of scalar product from a * b to c * c in all code
- Added more explanatory text (all marked with ###)

One-Dimensional Objects -
- Changed definition of a, b, & c to use np.array() instead of just the matrix itself
- Changed definition of the symmetry operations to return, instead of print (ex. changed print(np.dot(c,c)) to return np.dot(c,c) for scalar definition)

Four Symmetry Operations -
- Fixed mirroring across x-axis to be across y-axis

Operations on Scalar -
- Fixed all instances of operations applied to (a,b) instead of (c,c)
- Fixed mirroring across x-axis to be across y-axis

Symmetry Operations Table -
- Fixed my original table, which just had the exact outputs of the operations listed, to list either 1 or -1 instead based on the symmetry of the output
- Fixed mirroring across x-axis to be across y-axis

Questions -
- Answered questions at end of assignment originally overlooked!

### One-Dimensional Objects

In [36]:
# Importing numpy -
import numpy as np

# Constructing scalars, pseudoscalars, polar vectors, and axial vectors from these Cartesian vectors-
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])

### Defining the four objects -
def scalar(c):
    return np.dot(c,c) # Dot product ### Resubmission - changed to c dot c
def pseudoscalar(a, b, c):
    return np.dot(c, np.cross(a, b)) # Scalar triple product
def polarvector(c):
    return c # No operation
def axialvector(a, b):
    return np.cross(a, b) # Cross product

# Calling the objects -
print(scalar(c)) ### Dot product of a & b
print(pseudoscalar(a, b, c)) ### Scalar triple product of a, b, & c
print(polarvector(c)) ### No operation, just returning c
print(axialvector(a, b)) ### Cross product of a & b

1
1
[0 0 1]
[0 0 1]


#### Identity Operation

In [37]:
# Identity operation on a matrix -
identity = np.array(
     [[1, 0, 0]
     ,[0, 1, 0]     # The identity operation doesn't change anything here
     ,[0, 0, 1]]
     )

# Identity operation on my objects -
id_scalar = np.dot(identity @ c, identity @ c) ### Resubmission - changed to c dot c
print(id_scalar)

id_pseudoscalar = np.dot(identity @ c, np.cross(identity @ a, identity @ b))
print(id_pseudoscalar)

id_polarvector = identity @ c
print(id_polarvector)

id_axialvector = np.cross(identity @ a, identity @ b)
print(id_axialvector)

1
1
[0 0 1]
[0 0 1]


#### Four Symmetry Operations

In [65]:
# Defining symmetry operations -
inversion = np.array(         # Inversion operation
               [[-1, 0, 0]    # This inverts the x, y, and z direction of the object
               ,[0, -1, 0]
               ,[0, 0, -1]]
)

mirror_z = np.array(          # Mirroring in the xy-plane
               [[1, 0, -0]    # This inverts the z direction of the object
               ,[0, 1, -0]
               ,[0, 0, -1]]
)

mirror_y = np.array(          ### Mirroring in the xz-plane
               [[1, -0, 0]    ### This inverts the y direction of the object
               ,[0, -1, 0]
               ,[0, -0, 1]]
)

rotation_x_180 = np.array(    # Rotating 180 degrees about the x-axis
               [[1, -0, -0]   # This inverts y and z direction of the object
               ,[0, -1, -0]
               ,[0, -0, -1]]
)

#### Symmetry Operations on Scalar

In [60]:
# Applying to scalar -

inv_scalar = np.dot(inversion @ c, inversion @ c)            # Inverting scalar
print(inv_scalar)
mz_scalar = np.dot(mirror_z @ c, mirror_z @ c)               # Mirroring scalar in xy-plane
print(mz_scalar)
my_scalar = np.dot(mirror_y @ c, mirror_y @ c)               ### Mirroring scalar in xz-plane
print(my_scalar)
rx_scalar = np.dot(rotation_x_180 @ c, rotation_x_180 @ c)   # Rotating scalar 180 degrees about the x-axis
print(rx_scalar)

1
1
1
1


#### Symmetry Operations on Pseudoscalar

In [62]:
# Applying to pseudoscalar -

inv_pseudoscalar = np.dot(inversion @ c, np.cross((inversion @ a), (inversion @ b)))            # Inverting pseudoscalar
print(inv_pseudoscalar)
mz_pseudoscalar = np.dot(mirror_z @ c, np.cross(mirror_z @ a, mirror_z @ b))                    # Mirroring pseudoscalar in xy-plane
print(mz_pseudoscalar)
my_pseudoscalar = np.dot(mirror_y @ c, np.cross(mirror_y @ a, mirror_y @ b))                    ### Mirroring pseudoscalar in xz-plane
print(my_pseudoscalar)
rx_pseudoscalar = np.dot(rotation_x_180 @ c, np.cross(rotation_x_180 @ a, rotation_x_180 @ b))  # Rotating pseudoscalar 180 degrees about the x-axis
print(rx_pseudoscalar)

-1
-1
-1
1


#### Symmetry Operations on Polar Vector

In [57]:
# Applying to polar vector -

inv_polarvector = inversion @ c      # Inverting polar vector
print(inv_polarvector)
mz_polarvector = mirror_z @ c        # Mirroring polar vector in xy-plane
print(mz_polarvector)
my_polarvector = mirror_y @ c        ### Mirroring polar vector in xz-plane
print(my_polarvector)
rx_polarvector = rotation_x_180 @ c  # Rotating polar vector 180 degrees about the x-axis
print(rx_polarvector)

[ 0  0 -1]
[ 0  0 -1]
[0 0 1]
[ 0  0 -1]


#### Symmetry Operations on Axial Vector

In [59]:
# Applying to axial vector -

inv_axialvector = np.cross(inversion @ a, inversion @ b)           # Inverting axial vector
print(inv_axialvector)
mz_axialvector = np.cross(mirror_z @ a, mirror_z @ b)              # Mirroring axial vector in xy-plane
print(mz_axialvector)
my_axialvector = np.cross(mirror_y @ a, mirror_y @ b)              ### Mirroring axial vector in xz-plane
print(my_axialvector)
rx_axialvector = np.cross(rotation_x_180 @ a, rotation_x_180 @ b)  # Rotating axial vector 180 degrees about the x-axis
print(rx_axialvector)

[0 0 1]
[0 0 1]
[ 0  0 -1]
[ 0  0 -1]


#### Symmetry Operations Table

|1D Object    |Identity |Inversion |Mirror_z |Mirror_y |Rotation_x_180 |
|-------------|---------|----------|---------|---------|---------------|
|Scalar       |1        |1         |1        |1        |1              |
|Pseudoscalar |1        |-1        |-1       |-1       |1              |
|Polar Vector |1        |-1        |-1       |1        |-1             |
|Axial Vector |1        |1         |1        |-1       |-1             |

For the scalar object, we find that the symmetry is even under all operations.

For the pseudoscalar object, we find that the symmetry is even even under the identity and x-axis rotation operations, but odd under the inversion, z-axis mirror, and y-axis mirror operations.

For the polar vector object, we find that the symmetry is even under the identity and y-axis mirror operations, but odd under the inversion, z-axis mirror, and x-axis rotation operations.

For the axial vector object, we find that the symmetry is even under the identity, inversion, and z-axis mirror operations, but odd under the y-axis mirror and the x-axis rotation operations.

### Questions

#### 1. Are any of these operations redundant?
- The identity operation does not change any aspect of the object, only restating the original properties of the object- this could be considered redundant, but it serves as a helpful baseline for the rest of the symmetry table. In this symmetry table, the inversion operation and the mirroring across the z-axis operation happen to have the same outcome across the four objects, so together, they are redundant in this case- however, this may not the case for objects created from different coordinates. Mirroring across the y-axis and rotating 180 degrees about the x-axis both have unique symmetry outcomes in this table.

#### 2. Assigning the labels $Q_1$ to scalars, $Q_2$ to pseudoscalars, $Q_3$ to polar vectors, and $Q_4$ to axial vectors, and given that $Q_i, Q_j, Q_k$, etc. are coordinates of masses in a spring-mass system, are any terms $Q_i * Q_j$ possible? What about $Q_i * Q_j * Q_k$?
- For these springs to be coupled, their multiplied coordinates must be even under all symmetry operations. From the symmetry table above, there is no $Q_i * Q_j$ term that is even under all operations- however, $Q_2 * Q_3 * Q_4$ is possible! $Q_2 * Q_3$ (pseudoscalar * polar vector) creates a row of symmetry identities of (1, 1, 1, -1, -1). Multiplied by $Q_4$ (axial vector) results in a row of (1, 1, 1, 1, 1). The energy is even under all of these symmetries, so these objects can be coupled together- and of course, this $Q_2 * Q_3 * Q_4$ system can be multiplied by $Q_1$ (scalar) and maintain its even symmetry, so this system is possible as well.